gameroom/urls.py
from django.urls import path
from gameroom import views  # Import views from the current app


app_name = "gameroom"

urlpatterns = [
    # path("", views.pamplesneak, name="pamplesneak"),
    path("start/", views.joingame2, name="joingame2"),
    path("pampleplay/", views.pampleplay, name="pampleplay"),
    # path("pampleplay/create", views.creategame, name="creategame"),
    # path("pampleplay/join", views.joingame2, name="joingame2"),
    path(
        "pampleplay/<int:game_id>/<slug:slug>/timeline", views.timeline, name="timeline"
    ),
    path(
        "pampleplay/<int:game_id>/<slug:slug>/leaderboard",
        views.leaderboard,
        name="leaderboard",
    ),
    path("pampleplay/<int:game_id>/<slug:slug>/", views.joingame, name="joingame"),
    path("pampleplay/<int:game_id>/<slug:slug>/lobby", views.game_lobby, name="lobby"),
    path("send_word/<int:game_id>/<int:round_id>/", views.send_word, name="send_word"),
    path("ajax/inspiration/", views.get_inspiration, name="get_inspiration"),
    path(
        "ajax/refresh_word/<int:game_id>/<int:player_id>/",
        views.refresh_word,
        name="refresh_word",
    ),
    path(
        "ajax/word_success/<int:word_id>/<int:game_id>/<int:player_id>/",
        views.word_success,
        name="word_success",
    ),
    path(
        "ajax/word_fail/<int:word_id>/<int:game_id>/<int:player_id>/",
        views.word_fail,
        name="word_fail",
    ),
    path(
        "ajax/word_skip/<int:word_id>/<int:game_id>/<int:player_id>/",
        views.word_skip,
        name="word_skip",
    ),
    path(
        "ajax/validate_sneak/<int:game_id>/",
        views.validate_sneak,
        name="validate_sneak",
    ),
    path("ajax/reject_sneak/<int:game_id>/", views.reject_sneak, name="reject_sneak"),
    path("ajax/like_sneak/<int:game_id>/", views.like_sneak, name="like_sneak"),
    path("qr-code/<int:game_id>/<slug:slug>/", views.qr_code_view, name="qr_code"),
    # Desktop API
    path("api/create_game/", views.create_game, name="create_game"),
]

pamplesneak/urls.py
from django.contrib import admin
from django.urls import path, include
from pamplesneak import views as pamplesneak_views
from userprofile.views import user_games
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from pwa import views as pwa_views


urlpatterns = [
    path("", pamplesneak_views.home, name="home"),
    path("start/", pamplesneak_views.start, name="start"),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("gameroom/", include("gameroom.urls")),
    path("user/games/", user_games, name="user-games"),
    path("", include("pwa.urls")),
    path(
        "save_subscription/",
        pamplesneak_views.save_subscription,
        name="save_subscription",
    ),
    path(
        "update_or_save_subscription/",
        pamplesneak_views.update_or_save_subscription,
        name="update_or_save_subscription",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/models.py
from django.db import models

# Create your models here.

userprofile/views.py
from django.shortcuts import render
from gameroom.models import Game, Player


def user_games(request):
    if request.user.is_authenticated:
        # Get all Player instances for the current user
        player_instances = Player.objects.filter(user=request.user)

        # Retrieve the corresponding Game instances
        signed_up_games = [player.game for player in player_instances]

        return render(request, "userprofile/profile.html", {"games": signed_up_games})
    else:
        return render(request, "start.html")

userprofile/templates/userprofile/profile.html
{% extends "account/base.html" %}
{% load custom_filters %}

{% load i18n %}
{% load account %}
{% load static %}
{% load widget_tweaks %}


{% block jumbotron %}
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h1 class="text-2xl font-bold mb-2">Games Blessed by {{ user.username|possessive }} Presence</h1>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {% for game in games %}
            <div class="bg-gray-200 p-4 rounded">
                <h2 class="text-base md:text-lg">Game Name: <span class="text-muted">{{ game.game_name }}</span></h2>
                <h2 class="text-lg">Game Room Code: <span class="text-muted">{{ game.game_room_code }}</span></h2>
                <h2 class="text-lg">Active Players: <span class="text-muted">{{ game.number_of_players }}</span></h2>
                <div class="flex justify-center mt-4"> <!-- Flex container to center the button -->
                    <a class="bg-yellow-400 text-black font-bold py-2 px-4 rounded hover:bg-yellow-500" href="{% url 'gameroom:joingame' game_id=game.id slug=game.slug %}" role="button">Join Game!</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p>Please log in to view this page.</p>
{% endif %}
<!-- Content can go here if needed -->
{% endblock %}