gameroom/urls.py
from django.urls import path
from gameroom import views  # Import views from the current app


app_name = "gameroom"

urlpatterns = [
    # path("", views.pamplesneak, name="pamplesneak"),
    path("start/", views.joingame2, name="joingame2"),
    path("pampleplay/", views.pampleplay, name="pampleplay"),
    # path("pampleplay/create", views.creategame, name="creategame"),
    # path("pampleplay/join", views.joingame2, name="joingame2"),
    path(
        "pampleplay/<int:game_id>/<slug:slug>/timeline", views.timeline, name="timeline"
    ),
    path(
        "pampleplay/<int:game_id>/<slug:slug>/leaderboard",
        views.leaderboard,
        name="leaderboard",
    ),
    path("pampleplay/<int:game_id>/<slug:slug>/", views.joingame, name="joingame"),
    path("pampleplay/<int:game_id>/<slug:slug>/lobby", views.game_lobby, name="lobby"),
    path("send_word/<int:game_id>/<int:round_id>/", views.send_word, name="send_word"),
    path("ajax/inspiration/", views.get_inspiration, name="get_inspiration"),
    path(
        "ajax/refresh_word/<int:game_id>/<int:player_id>/",
        views.refresh_word,
        name="refresh_word",
    ),
    path(
        "ajax/word_success/<int:word_id>/<int:game_id>/<int:player_id>/",
        views.word_success,
        name="word_success",
    ),
    path(
        "ajax/word_fail/<int:word_id>/<int:game_id>/<int:player_id>/",
        views.word_fail,
        name="word_fail",
    ),
    path(
        "ajax/word_skip/<int:word_id>/<int:game_id>/<int:player_id>/",
        views.word_skip,
        name="word_skip",
    ),
    path(
        "ajax/validate_sneak/<int:game_id>/",
        views.validate_sneak,
        name="validate_sneak",
    ),
    path("ajax/reject_sneak/<int:game_id>/", views.reject_sneak, name="reject_sneak"),
    path("ajax/like_sneak/<int:game_id>/", views.like_sneak, name="like_sneak"),
    path("qr-code/<int:game_id>/<slug:slug>/", views.qr_code_view, name="qr_code"),
    # Desktop API
    path("api/create_game/", views.create_game, name="create_game"),
]

pamplesneak/urls.py
from django.contrib import admin
from django.urls import path, include
from pamplesneak import views as pamplesneak_views
from userprofile.views import user_games
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from pwa import views as pwa_views


urlpatterns = [
    path("", pamplesneak_views.home, name="home"),
    path("start/", pamplesneak_views.start, name="start"),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("gameroom/", include("gameroom.urls")),
    path("user/games/", user_games, name="user-games"),
    path("", include("pwa.urls")),
    path(
        "save_subscription/",
        pamplesneak_views.save_subscription,
        name="save_subscription",
    ),
    path(
        "update_or_save_subscription/",
        pamplesneak_views.update_or_save_subscription,
        name="update_or_save_subscription",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameroom/forms.py
# forms.py
from django import forms
from gameroom.models import Game, Round


class JoinGameForm(forms.Form):
    game_room_code = forms.CharField(
        max_length=6,
        widget=forms.TextInput(
            attrs={
                "class": "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline",
                "placeholder": "Game Code",
                "maxlength": "6",
            }
        ),
    )

    def clean_game_room_code(self):
        data = self.cleaned_data["game_room_code"]
        return data.upper()


class CreateGameForm(forms.ModelForm):
    NUMBER_OF_ROUNDS_CHOICES = [(i, str(i)) for i in range(1, 7)] + [
        ("open", "Open Ended Game")
    ]
    ROUND_DURATION_CHOICES = [
        (5, "5 minutes"),
        (10, "10 minutes"),
        (15, "15 minutes"),
        (30, "30 minutes"),
        (45, "45 minutes"),
        (60, "60 minutes"),
    ]

    SNEAK_CREATION_DURATION_CHOICES = [
        (5, "5 minutes"),
        (4, "4 minutes"),
        (3, "3 minutes"),
        (2, "2 minutes"),
        (1, "1 minute"),
    ]

    SNEAK_COUNT_CHOICES = [(i, str(i)) for i in range(1, 6)] + [
        ("unlimited", "no limits")
    ]

    number_of_rounds = forms.ChoiceField(choices=NUMBER_OF_ROUNDS_CHOICES, initial=3)
    play_state_duration = forms.ChoiceField(
        choices=ROUND_DURATION_CHOICES, required=False, initial=15
    )
    create_state_duration = forms.ChoiceField(
        choices=SNEAK_CREATION_DURATION_CHOICES, required=False, initial=3
    )
    sneaks_per_round = forms.ChoiceField(choices=SNEAK_COUNT_CHOICES, initial="3")
    allow_additional_sneaks = forms.BooleanField(required=False, initial=True)

    def clean_sneaks_per_round(self):
        sneaks_per_round = self.cleaned_data.get("sneaks_per_round")
        if sneaks_per_round == "unlimited":
            return 0
        return sneaks_per_round

    class Meta:
        model = Game
        fields = [
            "game_name",
            "number_of_rounds",
            "play_state_duration",
            "sneaks_per_round",
            "allow_additional_sneaks",
            "create_state_duration",
        ]
        widgets = {
            "game_name": forms.TextInput(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Game Name",
                    "maxlength": "32",
                }
            ),
            "number_of_rounds": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                }
            ),
            "play_state_duration": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                }
            ),
            "sneaks_per_round": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                }
            ),
            "create_state_duration": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                }
            ),
            "allow_additional_sneaks": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                }
            ),
        }


class RoundForm(forms.ModelForm):
    duration = forms.TimeField(widget=forms.TimeInput(attrs={"type": "time"}))

    class Meta:
        model = Round
        fields = ["duration"]


class MessageSender(forms.Form):
    word = forms.CharField(
        max_length=128,
        widget=forms.Textarea(  # Changed from TextInput to Textarea
            attrs={
                "class": "class_word form-input block w-full border border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50",
                "rows": 3,  # specify the number of rows
            }
        ),
        label="Word / Phrase",
    )
    target = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select block w-full border border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
            }
        )
    )
    send_anonymously = forms.BooleanField(
        initial=False, widget=forms.HiddenInput(), required=False
    )

    def __init__(self, players, *args, **kwargs):
        hide_target = kwargs.pop("hide_target", False)  # Add this line
        super().__init__(*args, **kwargs)
        self.fields["target"].choices = [(id, name) for id, name in players.items()]
        if hide_target:  # Conditionally hide the target field
            self.fields["target"].widget = forms.HiddenInput()
            self.fields["target"].required = False
        self.order_fields(["word", "target", "send_anonymously"])


class StartGameForm(forms.Form):
    pass

templates/custom_login.html
<form class="login" method="POST" action="{% url 'account_login' %}">
    {% csrf_token %}
    {{ login_form.as_p }}
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
      Log In
    </button>
</form>

templates/custom_signup.html
<form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
    {% csrf_token %}
    {{ signup_form.as_p }}
    <button type="submit"
      class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
      Sign Up
    </button>
</form>

templates/default_base.html
{% load static tailwind_tags pwa %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/png" href="{% static 'assets/images/favicon.png' %}" />

  <title>Pamplesneak!</title>

  <!-- Custom styles for this template -->
  <link href='https://fonts.googleapis.com/css?family=Berkshire+Swash' rel='stylesheet' type='text/css'>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  
  {% block head %}
  {% endblock %}
  {% tailwind_css %}
  {% progressive_web_app_meta %}
</head>

<body class="bg-lavender">
  <div id="page">
    <nav class="bg-white shadow-md fixed top-0 inset-x-0" role="navigation">
      <div class="container mx-auto px-6 py-3">
        <div class="flex justify-between">
          <div class="flex space-x-4">
            <div>
              <a class="flex items-center text-gray-800 hover:text-gray-600" href="/">
                <img src="{% static 'assets/images/logo.png' %}" height="50" width="50" alt="Logo">
              </a>
            </div>
            <!-- Primary Navbar items -->
            <div class="hidden md:flex items-center space-x-1">
              <!-- <a class="py-2 px-3 text-gray-700 hover:text-gray-900" href="/gameroom/pampleplay">Pamplesneak
                Lobby</a> -->
              {% if user.is_authenticated %}
                <a class="py-2 px-3 text-gray-700 hover:text-gray-900" href="{% url 'user-games' %}">{{ user.username }}'s Games</a>
                <a class="py-2 px-3 text-gray-700 hover:text-gray-900" href="{% url 'account_logout' %}">Log out</a>
              {% else %}
              <a class="py-2 px-3 text-gray-700 hover:text-gray-900" href="/">Log In / Sign Up</a>
              {% endif %}
            </div>
          </div>
          <!-- Mobile menu button -->
          <div class="md:hidden flex items-center">
            <button id="hamburger-button" class="mobile-menu-button">
              <svg class="w-6 h-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                viewBox="0 0 24 24" stroke="currentColor">
                <path d="M4 6h16M4 12h16M4 18h16"></path>
              </svg>
            </button>
          </div>
        </div>
      </div>
      <!-- mobile menu -->
      <div id="mobile-menu" class="mobile-menu hidden md:hidden">
        {% if user.is_authenticated %} 
          <a class="block py-2 px-4 text-sm hover:bg-gray-200" href="{% url 'user-games' %}">{{ user.username }}'s Games</a>
          <a class="block py-2 px-4 text-sm hover:bg-gray-200" href="{% url 'account_logout' %}">Log out</a>
        {% else %}
        <a class="block py-2 px-4 text-sm hover:bg-gray-200" href="/">Log In / Sign Up</a>
        {% endif %}
      </div>
    </nav>
  </div>

  <div id="jumbotron" class="mt-16">
    <div class="bg-gray-200 py-2">
      <div class="container mx-auto px-6">
        {% block jumbotron %}{% endblock %}
      </div>
    </div>
  </div>

  <div id="content" class="py-6">
    <div class="container mx-auto w-screen px-6">
      {% block content %}{% endblock %}
    </div>
  </div>
  <footer class="bg-white"></footer>

  {% block scripts %}
  <script>
    document.addEventListener('DOMContentLoaded', () => {
        // Setup for the hamburger menu
        const hamburger = document.getElementById('hamburger-button');
        const mobileMenu = document.getElementById('mobile-menu');

        hamburger.addEventListener('click', () => {
            mobileMenu.classList.toggle('hidden');
        });
    });
  </script>
  <script type="text/javascript">
    var vapid_public_key = "{{ VAPID_PUBLIC_KEY|safe }}";
  </script>
  <script>
    var csrf_token = "{{ csrf_token }}";
  </script>
  <script src="{% static 'js/push_subscriptions.js' %}"></script>
  {% endblock %}
  </body>
</html>

templates/index.html
{% extends "default_base.html" %}

{% load static %}

{% block jumbotron %}
<div class="flex flex-col h-screen">
index
</div>
{% endblock %}

{% block content %}
<!-- Additional content can go here -->
{% endblock %}

templates/login_or_register.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}
{% load static %}
{% load widget_tweaks %}


{% block jumbotron %}
{% endblock %}

{% block content %}
<div class="text-center py-6">
  <h1 class="text-2xl font-bold mb-2">Sign in or Register Today!</h1>
  <p class="mb-4">You must register in order to play!</p>
</div>

<div class="flex flex-col md:flex-row justify-center">
<!-- Login Section -->
<div class="md:w-1/2 bg-gray-300 p-4 mb-4 md:mb-0">
  <h1 class="text-lg font-bold">Log in</h1>
  {% include "custom_login.html" %}
</div>

<!-- Signup Section -->
<div class="md:w-1/2 bg-gray-200 p-4">
  <h1 class="text-lg font-bold">Sign Up</h1>
  {% include "custom_signup.html" %}
</div>
</div>
<!-- Content can go here if needed -->
{% endblock %}

templates/start.html
{% extends "default_base.html" %}

{% load static %}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'js/create_form.js' %}"></script>
{% endblock %}

{% block jumbotron %}
<div class="flex flex-col h-screen">

  <!-- JOIN Section -->
  <div class="w-full flex-grow" style="background-color: #1E7B4F; display: flex; align-items: center; justify-content: center;">
    <div class="text-center">
      <h1 class="text-4xl font-bold text-white">Join a Game</h1>
      <p class="text-lg text-white">Enter your game room code below.</p>
      <form action="{% url 'gameroom:joingame2' %}" method="post" class="flex justify-center items-center">
        {% csrf_token %}
        <div class="flex">
          {{ join_game.game_room_code }}
          <button type="submit" name="join_game" class="bg-yellow-400 text-black font-bold py-2 px-4 rounded hover:bg-yellow-500 ml-4">
            JOIN
          </button>
        </div>
      </form>
      {% if messages %}
        <div class="mt-4">
          {% for message in messages %}
            {% if 'logged in' not in message %}
                <div class="{{ message.tags }}">{{ message }}</div>
            {% endif %}
              <div class="{{ message.tags }}">{{ message }}</div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>
  
  <!-- HOST Section -->
  <div class="w-full flex-grow" style="background-color: #E7A13D; display: flex; align-items: center; justify-content: center;">
    <div class="text-center">
      <h1 class="text-4xl font-bold text-white">Host a Game</h1>
      <p class="text-lg text-white">What's the occasion?</p>
      <form action="{% url 'gameroom:joingame2' %}" method="POST" class="flex justify-center items-center">
        {% csrf_token %}
        <!-- Manually render form fields -->
        <div class="flex flex-col items-center">
          <div class="mb-4">
            {{ create_game.game_name }}
          </div>
          <div class="mb-4">
            <p class="text-lg text-white">Number of rounds</p>
            {{ create_game.number_of_rounds }}
          </div>
          <div class="mb-4">
            <p id="id_play_state_duration" class="text-lg text-white">Round duration</p>
            {{ create_game.play_state_duration }}
          </div>
          <div class="mb-4">
            <p id="id_sneaks_per_round" class="text-lg text-white">Sneaks per Round</p>
            {{ create_game.sneaks_per_round }}
          </div>
          <div class="mb-4">
            <p id="id_allow_additional_sneaks" class="text-lg text-white">Allow Additional Sneaks</p>
              {{ create_game.allow_additional_sneaks }}
          </div>
          <div class="mb-4">
            <p id="id_create_state_duration" class="text-lg text-white">Time for Sneak Creation</p>
            {{ create_game.create_state_duration  }}
          </div>
          <!-- Game Time Calculator Display -->
          <div class="mb-4">
            <p id="game-time-calculator" class="text-lg text-white">
                Estimated Total Game Time: <span id="total-game-time">0</span>
                <br>
                Estimated Conclusion Time: <span id="game-end-time"></span>
            </p>
          </div>
          <button type="submit" name="create_game" class="bg-blue-600 text-white font-bold py-2 px-4 rounded hover:bg-blue-700">
            HOST
          </button>
        </div>
      </form>
    </div>
  </div>
  <div>
  <br>
  <br>
  <br>
  <button id="subscribe" name="subscribe" class="bg-blue-600 text-white font-bold py-2 px-4 rounded hover:bg-blue-700">
    Subscribe to Notifications
  </button>
  </div>
  <br>
  <br>
  <br>
  </div>
{% endblock %}

{% block content %}
<!-- Additional content can go here -->
{% endblock %}