gameroom/urls.py
from django.urls import path
from gameroom import views  # Import views from the current app


app_name = "gameroom"

urlpatterns = [
    # path("", views.pamplesneak, name="pamplesneak"),
    path("start/", views.joingame2, name="joingame2"),
    path("pampleplay/", views.pampleplay, name="pampleplay"),
    # path("pampleplay/create", views.creategame, name="creategame"),
    # path("pampleplay/join", views.joingame2, name="joingame2"),
    path(
        "pampleplay/<int:game_id>/<slug:slug>/timeline", views.timeline, name="timeline"
    ),
    path(
        "pampleplay/<int:game_id>/<slug:slug>/leaderboard",
        views.leaderboard,
        name="leaderboard",
    ),
    path("pampleplay/<int:game_id>/<slug:slug>/", views.joingame, name="joingame"),
    path("pampleplay/<int:game_id>/<slug:slug>/lobby", views.game_lobby, name="lobby"),
    path("send_word/<int:game_id>/<int:round_id>/", views.send_word, name="send_word"),
    path("ajax/inspiration/", views.get_inspiration, name="get_inspiration"),
    path(
        "ajax/refresh_word/<int:game_id>/<int:player_id>/",
        views.refresh_word,
        name="refresh_word",
    ),
    path(
        "ajax/word_success/<int:word_id>/<int:game_id>/<int:player_id>/",
        views.word_success,
        name="word_success",
    ),
    path(
        "ajax/word_fail/<int:word_id>/<int:game_id>/<int:player_id>/",
        views.word_fail,
        name="word_fail",
    ),
    path(
        "ajax/word_skip/<int:word_id>/<int:game_id>/<int:player_id>/",
        views.word_skip,
        name="word_skip",
    ),
    path(
        "ajax/validate_sneak/<int:game_id>/",
        views.validate_sneak,
        name="validate_sneak",
    ),
    path("ajax/reject_sneak/<int:game_id>/", views.reject_sneak, name="reject_sneak"),
    path("ajax/like_sneak/<int:game_id>/", views.like_sneak, name="like_sneak"),
    path("qr-code/<int:game_id>/<slug:slug>/", views.qr_code_view, name="qr_code"),
    # Desktop API
    path("api/create_game/", views.create_game, name="create_game"),
]

pamplesneak/urls.py
from django.contrib import admin
from django.urls import path, include
from pamplesneak import views as pamplesneak_views
from userprofile.views import user_games
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from pwa import views as pwa_views


urlpatterns = [
    path("", pamplesneak_views.home, name="home"),
    path("start/", pamplesneak_views.start, name="start"),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("gameroom/", include("gameroom.urls")),
    path("user/games/", user_games, name="user-games"),
    path("", include("pwa.urls")),
    path(
        "save_subscription/",
        pamplesneak_views.save_subscription,
        name="save_subscription",
    ),
    path(
        "update_or_save_subscription/",
        pamplesneak_views.update_or_save_subscription,
        name="update_or_save_subscription",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameroom/views.py
from datetime import timedelta
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from gameroom.models import Game, Round, Player, Word, Vote, ExampleWord, Like
from users.models import UserProfile
from gameroom.forms import (
    MessageSender,
    CreateGameForm,
    RoundForm,
    JoinGameForm,
    StartGameForm,
)
from django.forms import formset_factory
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.contrib import messages
from django.conf import settings
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from .tasks import send_game_start_message, round_transition_state
import random
import json
import traceback
from django.urls import reverse

# QR Code Generation imports
import qrcode
from io import BytesIO
from django.http import HttpResponse
from django.utils import timezone


from rest_framework.decorators import api_view
from rest_framework.response import Response
from gameroom.utilities import send_push_notification


# getActiveGames function now utilizes Django ORM efficiently
def getActiveGames():
    return Game.objects.filter(active=True).order_by("-created")


def pampleplay(request):
    games_list = getActiveGames()  # Fetch the list of active games
    context = {"games_list": games_list}  # Pass the list of games to the template
    return render(request, "gameroom/play.html", context)


class GameInfo:
    def __init__(
        self,
        game_id,
        game_name,
        slug,
        active_players,
        max_players,
        word_bank_size,
        active,
    ):
        self.id = game_id
        self.game_name = game_name
        self.slug = slug
        self.active_players = active_players
        self.max_players = max_players
        self.word_bank_size = word_bank_size
        self.active = active


@login_required
def creategame(request):
    RoundFormSet = formset_factory(RoundForm, extra=0)

    if request.method == "POST":
        form = CreateGameForm(request.POST)
        round_formset = RoundFormSet(request.POST)

        if form.is_valid() and round_formset.is_valid():
            save_game = form.save(commit=False)
            save_game.active = True
            save_game.save()

            # Saving each round
            for round_form in round_formset:
                round_instance = round_form.save(commit=False)
                round_instance.game = save_game
                round_instance.save()

            # Auto-join the game creator as a player
            user = request.user
            player, created = Player.objects.get_or_create(
                game=save_game, user=user, defaults={"name": user.username}
            )

            # Assign the game to the user's profile
            user_profile, _ = UserProfile.objects.get_or_create(user=user)
            user_profile.current_game = save_game
            user_profile.current_player = player
            user_profile.save()

            # Redirect to the game view
            return redirect(
                "gameroom:joingame", game_id=save_game.id, slug=save_game.slug
            )
    else:
        form = CreateGameForm()
        round_formset = RoundFormSet()

    return render(
        request, "gameroom/create.html", {"form": form, "round_formset": round_formset}
    )


@login_required
@never_cache
def joingame(request, game_id, slug):
    game = get_object_or_404(Game, pk=game_id)

    current_round = Round.objects.get(game=game, round_number=game.current_round)
    user = request.user

    # Creating or retrieving the player
    player, created = Player.objects.get_or_create(
        game=game, user=user, defaults={"name": user.username}
    )

    # Handling UserProfile
    user_profile, _ = UserProfile.objects.get_or_create(user=user)

    # Assigning the current game to UserProfile
    user_profile.current_game = game
    user_profile.current_player = player
    user_profile.save()

    # Update the number of players
    game.number_of_players = Player.objects.filter(game=game).count()
    game.save()

    if game.active == False:
        return redirect("gameroom:lobby", game_id=game_id, slug=game.slug)

    all_players_query = Player.objects.filter(game=game)
    players_query = Player.objects.filter(game=game).exclude(id=player.id)
    players_dict = {p.id: p.name for p in players_query}

    hide_target = current_round.state == "create" or current_round.state == "transition"
    form = MessageSender(players_dict, hide_target=hide_target)

    words_submitted_this_round = Word.objects.filter(
        player=player, round=current_round
    ).count()

    # determine sneaks sent star count
    can_submit_more = words_submitted_this_round < current_round.sneaks_per_round
    # no_limits == true allows for any number of sneaks to be sent at the beginning of a round
    no_limits = False

    # unlimited_sneaks == true allows users to send additioanl sneaks while the round is in progress, otherwise sneaks are limited to between rounds.
    allow_additional_sneaks = current_round.allow_additional_sneaks
    if current_round.sneaks_per_round == 0:
        no_limits = True
        can_submit_more = True
        sneak_stars = words_submitted_this_round + 1
    else:
        sneak_stars = current_round.sneaks_per_round

    # Query to get the words associated with the player and game, not completed
    player_words = (
        Word.objects.filter(game=game_id)
        .filter(send_to=player)
        .filter(completed=False)
        .order_by("created")
    )

    # Get the count of words
    number_of_words = player_words.count()

    # Select the first word or None if the list is empty
    current_player_word = player_words[0] if player_words else None

    # Calculate the total sneaks allowed (assuming sneaks_range is a list or similar iterable)
    total_sneaks = sneak_stars

    # Calculate remaining sneaks
    remaining_sneaks = sneak_stars - words_submitted_this_round

    remaining_time = current_round.get_remaining_time()

    context = {
        "form": form,
        "word_bank_size": game.word_bank_size,
        "game": game,
        "player": player,
        "players": all_players_query.order_by("-succesful_sneaks"),
        "player_count": players_query.count(),
        "number_of_words": number_of_words,
        "player_word": current_player_word,
        "player_words": player_words,
        "range1_10": range(1, 11),
        "current_round": current_round,
        "can_submit_more": can_submit_more,
        "words_submitted_this_round": words_submitted_this_round,
        "remaining_time": remaining_time,
        "sneaks_range": range(1, sneak_stars + 1),
        "no_limits": no_limits,
        "allow_additional_sneaks": allow_additional_sneaks,
        "hide_target": hide_target,
        "remaining_sneaks": remaining_sneaks,
    }

    return render(request, "gameroom/ingame.html", context)


@login_required
@never_cache
def timeline(request, game_id, slug):
    game = get_object_or_404(Game, pk=game_id)
    current_round = Round.objects.get(game=game, round_number=game.current_round)
    user = request.user
    player, created = Player.objects.get_or_create(
        game=game, user=user, defaults={"name": user.username}
    )

    all_players_query = Player.objects.filter(game=game).order_by("-succesful_sneaks")

    all_sneaks = Word.objects.filter(
        game=game,
        completed=True,
    ).order_by("-time_completed")

    successful_sneaks = (
        Word.objects.filter(game=game, completed=True, successful=True)
        .select_related("player", "created_by")
        .order_by("-created")
    )

    failed_sneaks = (
        Word.objects.filter(game=game, completed=True, successful=False, skipped=False)
        .select_related("player", "created_by")
        .order_by("-created")
    )

    skipped_sneaks = (
        Word.objects.filter(game=game, completed=True, skipped=True)
        .select_related("player", "created_by")
        .order_by("-created")
    )

    received_sneaks = Word.objects.filter(
        game=game,
    ).select_related("player", "created_by")

    context = {
        "players": all_players_query,
        "all_sneaks": all_sneaks,
        "successful_sneaks": successful_sneaks,
        "failed_sneaks": failed_sneaks,
        "skipped_sneaks": skipped_sneaks,
        "received_sneaks": received_sneaks,
        "user_id": request.user.id,
        "player": player,
        "game": game,
        "current_round": current_round,
        "remaining_time": current_round.get_remaining_time(),
    }

    return render(request, "gameroom/timeline.html", context)


@login_required
@never_cache
def leaderboard(request, game_id, slug):
    game = get_object_or_404(Game, pk=game_id)
    current_round = Round.objects.get(game=game, round_number=game.current_round)
    user = request.user
    player, created = Player.objects.get_or_create(
        game=game, user=user, defaults={"name": user.username}
    )

    all_players_query = Player.objects.filter(game=game).order_by("-succesful_sneaks")

    all_sneaks = Word.objects.filter(game=game).order_by("-created")

    successful_sneaks = (
        Word.objects.filter(game=game, successful=True)
        .select_related("player", "created_by")
        .order_by("-created")
    )

    failed_sneaks = (
        Word.objects.filter(game=game, successful=False, skipped=False)
        .select_related("player", "created_by")
        .order_by("-created")
    )

    skipped_sneaks = (
        Word.objects.filter(game=game, skipped=True)
        .select_related("player", "created_by")
        .order_by("-created")
    )

    received_sneaks = Word.objects.filter(
        game=game,
    ).select_related("player", "created_by")

gameroom/templates/gameroom/filters.html
<div class="flex space-x-4">
    <!-- Filter Chips -->
    <div class="flex items-center space-x-2 mb-4">
        <!-- All Sneaks Filter Chip -->
        <button data-filter="all" class="filter-chip h-8 px-3 bg-gray-100 text-gray-800 rounded-full text-sm font-medium focus:outline-none">All</button>
        <!-- Successful Sneaks Filter Chip -->
        <button data-filter="successful" class="filter-chip h-8 px-3 bg-green-100 text-green-800 rounded-full text-sm font-medium focus:outline-none">Successful</button>
        <!-- Failed Sneaks Filter Chip -->
        <button data-filter="failed" class="filter-chip h-8 px-3 bg-red-100 text-red-800 rounded-full text-sm font-medium focus:outline-none">Failed</button>
        <!-- Skipped Sneaks Filter Chip -->
        <button data-filter="skipped" class="filter-chip h-8 px-3 bg-yellow-100 text-yellow-800 rounded-full text-sm font-medium focus:outline-none">Skipped</button>
    </div>
</div>

gameroom/templates/gameroom/ingame.html
{% extends "default_base.html" %}
{% load static %}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  var gameId = "{{ game.id }}";
  var playerId = "{{ player.id }}";
  var words_submitted_this_round = parseInt("{{ words_submitted_this_round }}", 10);
  var current_round = "{{ game.current_round }}";
  var number_of_rounds = "{{ game.number_of_rounds }}"
  var roundState = "{{ current_round.state }}";
  var countdownTimer = parseInt("{{ remaining_time|default:'0' }}", 10);
  console.log("start_remaining_time");
  console.log(countdownTimer);
  console.log("end_remaining_time");

</script>
<script src="{% static 'js/game_logic.js' %}"></script>
<script src="{% static 'js/lobby_socket.js' %}"></script>
{% endblock %}

{% block jumbotron %}
  <!-- Flex container with responsive direction -->
  <div class="flex flex-col md:flex-row justify-between items-center p-4">
    
    <!-- Left side: Game Info and Buttons, stacks on top on small screens -->
    <div class="min-h-[150px]">
      <h1 class="text-3xl font-bold">{{ game.game_name }}</h1>
      <h2 class="text-2xl">Game Room Code: {{ game.game_room_code }}</h2>
      
      <!-- Flex container with responsive design -->
      <div class="flex flex-col sm:flex-row my-4 space-y-2 sm:space-y-0 sm:space-x-2">
          <a href="{% url 'gameroom:timeline' game_id=game.id slug=game.slug %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded inline-block flex-grow text-center">
            Timeline
          </a>
          <a href="{% url 'gameroom:leaderboard' game_id=game.id slug=game.slug %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded inline-block flex-grow text-center">
            Leaderboard
        </a>
          <button id="show_qr_code_button" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded flex-grow">
              Show Share Game Code
          </button>
          <button id="hide_qr_code_button" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded hidden flex-grow">
              Hide Share Game Code
          </button>
      </div>
  </div>

  <!-- Right side: QR Code, moves below on small screens -->
  <div class="mt-4 md:mt-0 md:ml-4">
    <img src="{% url 'gameroom:qr_code' game_id=game.id slug=game.slug %}" alt="QR Code" id="qrCodeImage" style="height: 150px;" class="hidden">
  </div>

</div>
{% endblock %}

{% block content %}

{% if player_count > 0 %}
  {% if not game.ended %}
    <div id="game_info" class="flex flex-col items-center justify-center">
      <span id="currentRound" class="text-center"></span>
      <span id="gameState" class="text-center"></span>
      <span id="countdown" class="text-center"></span>
    </div>
  {% else %}
    <div id="end_game" class="flex items-center justify-center">
      <span class="text-center">Game has ended</span>
    </div>
  {% endif %}

  <div class="container mx-auto px-4">
    {% if messages %}
        <div id="message-container" class="fixed top-0 left-1/2 transform -translate-x-1/2 bg-green-500 text-white py-2 px-4 rounded-md text-center hidden">
            {% for message in messages %}
                <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
  </div>

  <div id="transitionState" class="container mx-auto px-4 py-4 text-center hidden" style="background-color: #1E7B4F;">
    <div class="my-4">
      <h1 class="text-xl font-bold">The round is about to start!!!</h1>
    </div>
  </div>
  
  <div id="playState" class="container mx-auto px-4 py-4 hidden" style="background-color: #1E7B4F;">
    <div class="my-4">
      {% include "gameroom/playerword.html" %}
    </div>
    <div class="container mx-auto px-4 py-4 text-center" style="background-color: #E7A13D;">
      {% include "gameroom/messageform.html" with form_type="play" %}
    </div>
  </div>
  
  <div id="createState" class="container mx-auto px-4 py-4 text-center hidden" style="background-color: #E7A13D;">
    {% include "gameroom/messageform.html" with form_type="create"%}
  </div>

{% else %}
  <div class="container mx-auto px-4 text-center">
    <p class="text-xl font-bold">Waiting for more players.</p>
    <p class="text-xl font-bold">Invite the people around you!</p>
  </div>
{% endif %}

{% block scripts %}

{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% endblock %}

gameroom/templates/gameroom/leaderboard.html
{% extends "default_base.html" %}
{% load static %}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  var gameId = "{{ game.id }}";
  var playerId = "{{ player.id }}";
</script>
<script src="{% static 'js/game_logic.js' %}"></script>
{% endblock %}

{% block jumbotron %}
  <!-- Flex container with responsive direction -->
  <div class="flex flex-col md:flex-row justify-between items-center p-4">
    
    <!-- Left side: Game Info and Buttons, stacks on top on small screens -->
    <div class="min-h-[150px]">
      <h1 class="text-3xl font-bold">{{ game.game_name }}</h1>
      <h2 class="text-2xl">Game Room Code: {{ game.game_room_code }}</h2>
      
      <!-- Flex container with responsive design -->
      <div class="flex flex-col sm:flex-row my-4 space-y-2 sm:space-y-0 sm:space-x-2">
        <a href="{% url 'gameroom:joingame' game_id=game.id slug=game.slug %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded inline-block text-center">
            Back to the game!
        </a>
        <a href="{% url 'gameroom:timeline' game_id=game.id slug=game.slug %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded inline-block text-center">
            Timeline!
        </a>
        <button id="show_qr_code_button" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded flex-grow">
            Show Share Game Code
        </button>
        <button id="hide_qr_code_button" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded hidden flex-grow">
            Hide Share Game Code
        </button>
      </div>
  </div>

    <!-- Right side: QR Code, moves below on small screens -->
    <div class="mt-4 md:mt-0 md:ml-4">
      <img src="{% url 'gameroom:qr_code' game_id=game.id slug=game.slug %}" alt="QR Code" id="qrCodeImage" style="height: 150px;" class="hidden">
    </div>
  
  </div>
{% endblock %}

{% block content %}

<div class="container mx-auto p-4"> 
    <!-- Gradient Background Wrapper -->
    <div class="relative overflow-hidden bg-gradient-to-r from-blue-100 to-indigo-100 p-4 rounded-lg shadow-md">
    <!-- Full width for the leaderboard with more vibrant background -->
    <h2 class="text-3xl font-bold mb-4 text-center text-indigo-700">🏆 Leaderboard 🏆</h2>
    {% if players %}
        <!-- Pseudo-element for Gradient Header -->
        <div class="overflow-x-auto relative">
            <div class="absolute inset-0 bg-gradient-to-l from-indigo-500 to-purple-600 rounded-t-lg opacity-75"></div>
            <table class="w-full text-sm divide-y divide-gray-200 relative z-10">
                <thead class="text-white">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-left font-medium">Player</th>
                        <th scope="col" class="px-6 py-3 text-left font-medium">Successful Sneaks</th>
                        <th scope="col" class="px-6 py-3 text-left font-medium">Failed Sneaks</th>
                        <th scope="col" class="px-6 py-3 text-left font-medium">Skipped Sneaks</th>
                        <th scope="col" class="px-6 py-3 text-left font-medium">Likes</th>
                        <th scope="col" class="px-6 py-3 text-left font-medium">Received Sneaks</th>
                    </tr>
                </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {% for player in players %}
                            <tr class="hover:bg-gray-100 transition duration-150 ease-in-out">
                                <td class="px-6 py-4 font-medium text-gray-900 flex items-center">
                                    {{ player.name }}
                                    {% if forloop.counter == 1 %}
                                        <span class="ml-2">🥇</span>
                                    {% elif forloop.counter == 2 %}
                                        <span class="ml-2">🥈</span>
                                    {% elif forloop.counter == 3 %}
                                        <span class="ml-2">🥉</span>
                                    {% endif %}
                                </td>
                                <td class="px-6 py-4">
                                    <span class="inline-flex items-center justify-center px-2 py-1 text-xs font-semibold leading-none text-green-800 bg-green-200 rounded-full">{{ player.succesful_sneaks }} 🌟</span>
                                </td>
                                <td class="px-6 py-4">
                                    <span class="inline-flex items-center justify-center px-2 py-1 text-xs font-semibold leading-none text-red-800 bg-red-200 rounded-full">{{ player.failed_sneaks }} 💥</span>
                                </td>
                                <td class="px-6 py-4">
                                    <span class="inline-flex items-center justify-center px-2 py-1 text-xs font-semibold leading-none text-yellow-800 bg-yellow-200 rounded-full">{{ player.skipped_sneaks }} ⏭</span>
                                </td>
                                <td class="px-6 py-4">
                                    <span class="inline-flex items-center justify-center px-2 py-1 text-xs font-semibold leading-none text-pink-800 bg-pink-200 rounded-full">{{ player.likes }} ❤️</span>
                                </td>
                                <td class="px-6 py-4">
                                    {{ player.received_sneaks }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p class="text-gray-500 text-center">No sneaky stats yet 🕵️‍♂️</p>
        {% endif %}
    </div>
</div>

{% endblock %}

gameroom/templates/gameroom/timeline.html
{% extends "default_base.html" %}
{% load static %}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  var gameId = "{{ game.id }}";
  var playerId = "{{ player.id }}";
</script>
<script src="{% static 'js/game_logic.js' %}"></script>
{% endblock %}

{% block jumbotron %}
  <!-- Flex container with responsive direction -->
  <div class="flex flex-col md:flex-row justify-between items-center p-4">
    
    <!-- Left side: Game Info and Buttons, stacks on top on small screens -->
    <div class="min-h-[150px]">
      <h1 class="text-3xl font-bold">{{ game.game_name }}</h1>
      <h2 class="text-2xl">Game Room Code: {{ game.game_room_code }}</h2>
      
      <!-- Flex container with responsive design -->
      <div class="flex flex-col sm:flex-row my-4 space-y-2 sm:space-y-0 sm:space-x-2">
        <a href="{% url 'gameroom:joingame' game_id=game.id slug=game.slug %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded inline-block text-center">
            Back to the game!
        </a>
        <a href="{% url 'gameroom:leaderboard' game_id=game.id slug=game.slug %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded inline-block text-center">
            Leaderboard!
        </a>
        <button id="show_qr_code_button" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded flex-grow">
            Show Share Game Code
        </button>
        <button id="hide_qr_code_button" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded hidden flex-grow">
            Hide Share Game Code
        </button>
      </div>
  </div>

    <!-- Right side: QR Code, moves below on small screens -->
    <div class="mt-4 md:mt-0 md:ml-4">
      <img src="{% url 'gameroom:qr_code' game_id=game.id slug=game.slug %}" alt="QR Code" id="qrCodeImage" style="height: 150px;" class="hidden">
    </div>
  
  </div>
{% endblock %}

{% block content %}

{% include "gameroom/filters.html" %}

<div class="space-y-8 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-slate-300 before:to-transparent">
    <h2 id="sneaksTitle" class="text-2xl font-bold mb-4">All Sneaks</h2>
    {% for sneak in all_sneaks %}
    <div id="{{ sneak.id }}" data-status="{% if sneak.successful %}successful{% elif sneak.skipped %}skipped{% else %}failed{% endif %}" class="card relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group">
        <!-- Icon Placeholder - Customize based on sneak's status -->
        <div class="flex items-center justify-center w-10 h-10 rounded-full border border-white bg-slate-300 text-slate-500 shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2">
            <!-- Dynamic SVG icon can be added here based on the sneak's status -->
        </div>
        <!-- Card Content -->
        <div class="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-white p-4 rounded border border-slate-200 shadow">
            <div class="mt-2">
                {% if sneak.successful %}
                    <span class="text-green-500 text-xl font-bold">🌟 Success</span>
                {% elif sneak.skipped %}
                    <span class="text-yellow-500 text-xl font-bold">⏭ Skip</span>
                {% else %}
                    <span class="text-red-500 text-xl font-bold">❌ Fail</span>
                {% endif %}
            </div>
            <div class="text-slate-500">
                <time class="font-caveat font-medium text-indigo-500">{{ sneak.created|date:"d/m/Y H:i" }}</time>
                <p>{{ sneak.created_by.name }} => {{ sneak.send_to.name }}</p>
            </div>
            <div class="flex items-center justify-between space-x-2 mb-1">
                <div class="font-bold text-slate-900">"{{ sneak.word }}"</div>
            </div>
            <!-- Voting and Like Mechanism -->
            <div>
                {% if sneak.successful %}
                    <button class="validate_sneak mr-2 px-2 py-1 bg-green-500 text-white rounded">Validate</button>
                    <button class="reject_sneak px-2 py-1 bg-red-500 text-white rounded">Reject</button>
                {% endif %}
                <button class="like_sneak px-2 py-1 bg-blue-500 text-white rounded">Like</button>
            </div>
            <!-- Display validations and rejections if successful -->
            <div class="votes">
                {% if sneak.successful %}
                    <p>
                        Validations: <strong class="validation-count">{{ sneak.validations_count }} 🌟</strong>,
                        Rejections: <strong class="rejection-count">{{ sneak.rejections_count }} 💔</strong>,
                    </p>
                {% endif %}
                Likes: <strong class="like-count">{{ sneak.likes_count }} ❤️</strong>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}